baseurl = "/"
title = "Uncombed Whiskers"
languageCode = "en-us"
paginate = "6" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-100945032-1" # Enable Google Analytics by entering your tracking id
enableEmoji = "true"

[Author]
    name = "Shahid Khan"
    bio = "Perennial Code Tinkerer; Loves metal, historial fiction & lego"
    avatar = "img/avatar.png"

[Params]
    subtitle = "Ramblings of a bit tinkerer" # Subtitle of your site
    description = " Personal blog about tech & life" # Description of your site
    opengraph = true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false
    post_navigation = true

[Params.widgets]
    search = false 
    recent_articles = true
    categories = true 
    tags = true
    tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
    social = true
    social_twitter = "talltoast"
    social_linkedin = "shakhan"
    social_github = "tallstoat"

